#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 28 13:37:46 2021

@author: nikolaj
"""

#Project 1: Bakterie-Dataanalyse

#Main script
#	Laves til sidst
#	

#Data Load Function Gustav
#	Leg lidt med matricer (index, muligvis slicing)
#	Og det at loade filer

#Data Statistics Function Nikolaj
#	Man skal kunne (numpy) funktioner der beregner middelværdi m.m. ud fra en matrix
#	
import numpy as np

#   testData
data = testData = np.array([[1,2,3],[1,2,3],[52,2,52],[1,2,4],[9,10,11],[2,3,4]])
statistic = testStat = "Std Growth Rate"

temp = data[:,0]
growth_Rate = data[:,1]
bacteria = data[:,2]

rows,col = np.shape(data) 

statStr = np.array(["mean temperature","mean growth rate","std temperature","std growth rate",
                    "rows","mean cold growth rate","mean hot growth rate"])
statFlo = np.array([np.mean(temp),np.mean(growth_Rate),np.std(temp),np.std(growth_Rate),
                    rows,np.mean(temp[temp<20]),np.mean(temp[temp>50])])

#array med den efterspurgte statistiske værdi
expectedStat = ((statStr==statistic.lower())*statFlo)

try:
    result = expectedStat[expectedStat!=0][0]
except IndexError:
    result = 0
#finally:
#    return result



#Data Plot Function Benjamin
#	Grafer
#	



